apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}
  labels:
    app: {{ .Values.general.app }}
    name: {{ .Values.worker.name }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.general.app }}
      name: {{ .Values.worker.name }}
  template:
    metadata:
      name: {{ .Values.worker.name }}
      labels:
        app: {{ .Values.general.app }}
        name: {{ .Values.worker.name }}
    spec:
      containers:
      - name: {{ .Values.worker.name }}
        image: {{ .Values.worker.image }}:{{ .Values.worker.imageTag }}
        imagePullPolicy: {{ .Values.worker.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.worker.resources.requests.cpu | quote }}
            memory: {{ .Values.worker.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.worker.resources.limits.cpu | quote }}
            memory: {{ .Values.worker.resources.limits.memory | quote }}
        envFrom:
        - secretRef:
            name: {{ .Values.postgres.secretName }}
