apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
type: Opaque
data:
  POSTGRES_USER: {{ printf "%s" .Values.secrets.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ printf "%s" .Values.secrets.postgresPassword | b64enc }}
  POSTGRES_DB: {{ printf "%s" .Values.secrets.postgresDb | b64enc }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.secrets.postgresUser .Values.secrets.postgresPassword .Values.postgres.name .Values.postgres.port .Values.secrets.postgresDb | b64enc }}
