apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}      
spec:
  type: ClusterIP            
  selector:
    name: {{ .Values.api.name }}              
  ports:
  - protocol: TCP
    port:  {{ .Values.api.port }}                 
    targetPort: {{ .Values.api.port }}