apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
spec:
  clusterIP: None
  selector:
    name: {{ .Values.postgres.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}