apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}      
spec:
  type: ClusterIP            
  selector:
    name: {{ .Values.redis.name }}              
  ports:
  - protocol: TCP
    port: {{ .Values.redis.port }}                 
    targetPort: {{ .Values.redis.port }}  