apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
spec:
  type: {{ .Values.web.serviceType | default "ClusterIP" }}
  selector:
    name: {{ .Values.web.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
